-- ----------------------------- ORDER BASE TABLES ----------------------------------
CREATE TABLE `BAZZAR`.`ORDER` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT,
	`INVOICE_NUMBER` BIGINT ( 30 ) NOT NULL,
	`TRACKING_NUMBER` BIGINT ( 30 ) NULL,
	`PURCHASE_DATE` DATETIME NULL,
	`CANCELED_DATE` DATETIME NULL,
	`REFUNDED_DATE` DATETIME NULL,
	`SHIPPED_DATE` DATETIME NULL,
	`BEFORE_TAX_TOTAL` DECIMAL(13,2) NULL DEFAULT '0.00',
	`SHIPPING_TOTAL` DECIMAL(13,2) NULL DEFAULT '0.00',
	`REFUNDABLE_TOTAL` DECIMAL(13,2) NULL DEFAULT '0.00',
	`ORDER_TOTAL` DECIMAL(13,2) NULL DEFAULT '0.00',
	`ORDER_TAX` DECIMAL(13,2) NULL DEFAULT '0.00',
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ORDER_DETAIL` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT,
	`ITEM_ID` BIGINT ( 30 ) NOT NULL,
	`ITEM_PRICE` DECIMAL(13,2) NOT NULL DEFAULT '0.00',
	`QTY` BIGINT ( 30 ) NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ------------------------ ORDER LINK TABLES -------------------------------
CREATE TABLE `BAZZAR`.`ORDER_ADDRESS` (
	`ADDRESS_ID` BIGINT ( 30 ) NOT NULL, 
	`ORDER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ADDRESS_ID`, `ORDER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ORDERS_DETAIL` (
	`DETAIL_ID` BIGINT ( 30 ) NOT NULL, 
	`ORDER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `DETAIL_ID`, `ORDER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ORDER_ITEM` (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL, 
	`ORDER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`, `ORDER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ORDER_SHIPPING` (
	`SHIPPING_ID` BIGINT ( 30 ) NOT NULL, 
	`ORDER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `SHIPPING_ID`, `ORDER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ORDER_CUSTOMER` (
	`CUSTOMER_ID` BIGINT ( 30 ) NOT NULL, 
	`ORDER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `CUSTOMER_ID`, `ORDER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ORDER_NOTE` (
	`NOTE_ID` BIGINT ( 30 ) NOT NULL, 
	`ORDER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `NOTE_ID`, `ORDER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ----------------------------- SHOPPING CART BASE TABLES --------------------------
CREATE TABLE `BAZZAR`.`SHOPPINGCART` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT,
	`SHOPPINGCART_CREATED` DATETIME NOT NULL,
	`SHOPPINGCART_SEND` DATETIME NOT NULL,
	`SHOPPINGCART_CANCELED` DATETIME NOT NULL,
	`SHOPPINGCART_SAVED` DATETIME NOT NULL,
	`SHOPPINGCART_SUB_TOTAL` DECIMAL(13,2) NULL DEFAULT '0.00',
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ------------------------ SHOPPING CART LINK TABLES -------------------------------
CREATE TABLE `BAZZAR`.`SHOPPINGCART_DETAIL` (
	`DETAIL_ID` BIGINT ( 30 ) NOT NULL, 
	`SHOPPINGCART_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `DETAIL_ID`, `SHOPPINGCART_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`SHOPPINGCART_ITEM` (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL, 
	`SHOPPINGCART_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`, `SHOPPINGCART_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`SHOPPINGCART_NOTE` (
	`NOTE_ID` BIGINT ( 30 ) NOT NULL, 
	`SHOPPINGCART_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `NOTE_ID`, `SHOPPINGCART_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ------------------------ GENERAL TABLES -------------------------------
CREATE TABLE `BAZZAR`.`NOTE` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT,
	`NOTE` VARCHAR ( 2500 ) NOT NULL,
	`NOTE_TYPE` BIGINT ( 30 ) NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ----------------------------- ITEM BASE TABLES ----------------------------------
CREATE TABLE `BAZZAR`.`REVIEW` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT,
	`REVIEW` VARCHAR ( 2500 ) NOT NULL,
	`REVIEW_DATE` DATETIME NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`PICTURES` ( 
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`PICTURE_LOCATION` VARCHAR ( 100 ) NOT NULL, 
	`DESCRIPTION` VARCHAR ( 2500 )  NOT NULL, 
	`ALT` VARCHAR(200) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`WEIGHT` ( 
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY_GROUP` VARCHAR ( 100 ) NULL, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`DEMENSIONS` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY_GROUP` VARCHAR ( 100 ) NULL, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`DETAIL` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`MANUFACTURE` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`NAME` VARCHAR ( 500 )  NOT NULL, 
	`NUMBER` VARCHAR ( 100 ) NULL,
	`AUTHORIZE_PICTURE` TINYINT ( 1 ) NOT NULL DEFAULT '0',
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ITEM` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`SUBJECT` VARCHAR ( 2500 )  NOT NULL, 
	`SPECIAL_OFFER_PRICE` DECIMAL(13,2) NOT NULL DEFAULT '0.00', 
	`SPECIAL_PRICE_START` DATE NULL, 
	`SPECIAL_PRICE_END` DATE NULL, 
	`SPECIAL_PRICE_ACTIVE` TINYINT ( 1 ) NOT NULL DEFAULT '0', 
	`SALE_PRICE` DECIMAL(13,2) NOT NULL DEFAULT '0.00', 
	`LISTED_PRICE` DECIMAL(13,2) NOT NULL DEFAULT '0.00', 
	`QTY` INT (10) NOT NULL DEFAULT '0', 
	`REBATE` TINYINT ( 1 ) NOT NULL DEFAULT '0', 
	`IN_STOCK` TINYINT ( 1 ) NOT NULL DEFAULT '0', 
	`MANUFACTURE_MODEL_NUMBER` VARCHAR ( 100 ) NULL, 
	`BAR_CODE` BIGINT ( 20 ) NULL DEFAULT '0',
	`AVERAGE_CUSTOMER_RATING` TINYINT ( 2 ) NULL DEFAULT '0',
	`PAGE_LOCATOR` VARCHAR ( 250 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`FEATURES` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`SPECIFICATIONS` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`WARRANTY` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY_GROUP` VARCHAR ( 100 ) NULL, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`SHIPPING` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CATEGORY_GROUP` VARCHAR ( 100 ) NULL, 
	`CATEGORY` VARCHAR ( 100 ) NULL, 
	`ATTRIBUTE` VARCHAR ( 500 )  NOT NULL, 
	`VALUE` VARCHAR ( 2500 )  NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ACCESSORIES` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`ITEM_ID` BIGINT ( 30 ) NOT NULL, 
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ITEMLACATOR` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`PAGE_LOCATION` VARCHAR ( 200 ) NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.QA (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`QA` VARCHAR ( 2000 ) NOT NULL,
	`ANSWER` VARCHAR ( 2000 ) NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.RATING (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`RATING` INT ( 2 ) NOT NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- some kind of serarch table....... Need to design. 
-- ------------------------ ITEM LINK TABLES -------------------------------
CREATE TABLE `BAZZAR`.ITEM_QA (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL, 
	`QA_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`, `QA_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.MANUFACTURE_PICTURE (
	`MANUFACTURE_ID` BIGINT ( 30 ) NOT NULL, 
	`PICTURE_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY( MANUFACTURE_ID, `PICTURE_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_MANUFACTURE (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`MANUFACTURE_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`MANUFACTURE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_SPECIFICATION (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`SPECIFICATION_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`SPECIFICATION_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_DETAIL (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`DETAIL_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`DETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_ACCESSORIES (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`ACCESSORIES_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`ACCESSORIES_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_DEMENSIONS (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`DEMENSIONS_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`DEMENSIONS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_RATING (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`RATING_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`RATING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_FEATURES (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`FEATURES_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`FEATURES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_WEIGHT (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`WEIGHT_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`WEIGHT_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_WARRANTY (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`WARRANTY_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`WARRANTY_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_PICTURES (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`PICTURES_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`PICTURES_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_CUSTOMER (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`CUSTOMER_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`CUSTOMER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_REVIEW (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`REVIEW_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`REVIEW_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.ITEM_SHIPPING (
	`ITEM_ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`SHIPPING_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `ITEM_ID`,`SHIPPING_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ----------------------------- Menue Base Tables ---------------------------------
CREATE TABLE `BAZZAR`.`CATEGORY` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`ATTRIBUTE` VARCHAR ( 500 ) NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`SUBCATEGORY` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`ATTRIBUTE` VARCHAR ( 500 ) NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`PRODUCT` (
	`ID` BIGINT ( 30 ) NOT NULL AUTO_INCREMENT, 
	`ATTRIBUTE` VARCHAR ( 500 ) NOT NULL, 
	`DISPLAY_OPTION` VARCHAR ( 100 ) NULL,
	`CREATED` DATETIME NOT NULL,
	`UPDATED` DATETIME NOT NULL,
	`STATUS` TINYINT NULL,
	PRIMARY KEY ( `ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- --------------------------- Menue Link Table ----------------------------------
CREATE TABLE `BAZZAR`.`CATEGORY_SUBCATEGORY` (
	`CATEGORY_ID` BIGINT ( 30 ) NOT NULL, 
	`SUBCATEGORY_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `CATEGORY_ID`, `SUBCATEGORY_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`SUBCATEGORY_PRODUCT` (
	`SUBCATEGORY_ID` BIGINT ( 30 ) NOT NULL, 
	`PRODUCT_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `SUBCATEGORY_ID`, `PRODUCT_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`PRODUCT_PICTURE` (
	`PRODUCT_ID` BIGINT ( 30 ) NOT NULL, 
	`PICTURE_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `PRODUCT_ID`,`PICTURE_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`PRODUCT_ITEM` (
	`PRODUCT_ID` BIGINT ( 30 ) NOT NULL, 
	`ITEM_ID` BIGINT ( 30 ) NOT NULL,
	PRIMARY KEY ( `PRODUCT_ID`,`ITEM_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 -- ----------------------------- Person Base Tables --------------------------------
 CREATE TABLE `BAZZAR`.`CUSTOMER` (
   `ID` bigint(30) NOT NULL,
   `TYPE` varchar(20) NOT NULL,
   `PREFIX` bigint(20) DEFAULT NULL,
   `FIRST_NAME` varchar(50) NOT NULL,
   `MIDDLE_NAME` varchar(50) DEFAULT NULL,
   `LAST_NAME` varchar(100) DEFAULT NULL,
   `DOB` date DEFAULT NULL,
   `CREATED` datetime NOT NULL,
   `UPDATED` datetime NOT NULL,
   `STATUS` TINYINT NULL,
   PRIMARY KEY (`ID`),
   KEY `ID` (`LAST_NAME`,`FIRST_NAME`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 -- INSERT INTO user_sha1 VALUES ('member1',SHA1('secretpassword') ) 
 -- SELECT * FROM user_sha1 WHERE user_name='member1' AND password=SHA1('secretpassword') 
CREATE TABLE `BAZZAR`.`USER` (
 	`ID` BIGINT (30) NOT NULL AUTO_INCREMENT,
 	`USERNAME` VARCHAR ( 50 ) NOT NULL,
 	`PASSWORD` VARCHAR ( 40 ) NOT NULL,
 	`CREATED` DATETIME NOT NULL,
 	`UPDATED` DATETIME NOT NULL,
 	`STATUS` TINYINT NULL,
 	PRIMARY KEY ( `ID` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`SUBSCRIPTION` (
  	`ID` BIGINT (30) NOT NULL AUTO_INCREMENT,
  	`PROMOTIONAL` TINYINT NULL,
  	`NEWLATTER` TINYINT NULL,
  	`COUPONS` TINYINT NULL,
  	`CREATED` DATETIME NOT NULL,
  	`UPDATED` DATETIME NOT NULL,
  	`STATUS` TINYINT NULL,
  	PRIMARY KEY ( `ID` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`AUTORITIES` (
    `ID` BIGINT(30) NOT NULL,
    `USER_ID` BIGINT (30) NOT NULL,
    `AUTHORITY` varchar (50) NOT NULL,
    `CREATED` datetime NOT NULL,
    `UPDATED` datetime NOT NULL,
    `STATUS` TINYINT NULL,
    PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 CREATE TABLE `BAZZAR`.`CREDITCARD` (
 	`ID` BIGINT (30) NOT NULL AUTO_INCREMENT,
 	`TYPE` VARCHAR ( 20 ) NOT NULL,
 	`NUMBER` INT ( 20 ) NOT NULL,
 	`EXP_MONTH` BIGINT (30) NOT NULL,
 	`EXP_YEAR` BIGINT (30) NOT NULL,
 	`CARDHOLDER_NAME` VARCHAR ( 100 ) NOT NULL,
 	`CREATED` DATETIME NOT NULL,
 	`UPDATED` DATETIME NOT NULL,
 	`STATUS` TINYINT NULL,
 	PRIMARY KEY ( `ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`EMAIL` (
 	`ID` BIGINT (30) NOT NULL AUTO_INCREMENT,
 	`TYPE` VARCHAR ( 20 ) NOT NULL,
 	`EMAIL` VARCHAR ( 100 ) NOT NULL,
 	`CREATED` DATETIME NOT NULL,
 	`UPDATED` DATETIME NOT NULL,
 	`STATUS` TINYINT NULL,
 	PRIMARY KEY ( `ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PHONE` (
 	`ID` BIGINT (30) NOT NULL AUTO_INCREMENT,
 	`TYPE` VARCHAR ( 20 ) NOT NULL,
 	`COUNTRY_CODE` VARCHAR ( 10 ) NULL,
 	`AREA_CODE` VARCHAR ( 10 ) NULL,
 	`NUMBER` VARCHAR ( 20 ) NOT NULL,
 	`EXTENSION` VARCHAR ( 10 ) NULL,
 	`CREATED` DATETIME NOT NULL,
 	`UPDATED` DATETIME NOT NULL,
 	`STATUS` TINYINT NULL,
 	PRIMARY KEY ( `ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`ADDRESS` (
 	`ID` BIGINT (30) NOT NULL AUTO_INCREMENT,
 	`TYPE` VARCHAR ( 20 ) NOT NULL,
 	`ADDRESS_1` VARCHAR ( 250 ) NOT NULL,
 	`ADDRESS_2` VARCHAR ( 250 ) NULL,
 	`ADDRESS_3` VARCHAR ( 250 ) NULL,
 	`COUNTRY_CODE` VARCHAR ( 100 ) NOT NULL,
 	`CITY` VARCHAR ( 100 ) NOT NULL,
 	`STATE` VARCHAR ( 100 ) NULL,
 	`ZIP` VARCHAR ( 10 ) NOT NULL,
 	`ZIP_PLUS` VARCHAR ( 10 ) NULL,
 	`CREATED` DATETIME NOT NULL,
 	`UPDATED` DATETIME NOT NULL,
 	`STATUS` TINYINT NULL,
 	PRIMARY KEY ( `ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 -- ----------------------------- Person Link Tables --------------------------------
 CREATE TABLE `BAZZAR`.`PERSON_ADDRESS` (
 	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
 	`ADDRESS_ID` BIGINT ( 30 ) NOT NULL,
 	PRIMARY KEY ( `PERSON_ID`,`ADDRESS_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSON_SUBSCRIPTION` (
  	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
  	`SUBSCRIPTION_ID` BIGINT ( 30 ) NOT NULL,
  	PRIMARY KEY ( `PERSON_ID`,`SUBSCRIPTION_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSON_USER` (
 	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
 	`USER_ID` BIGINT ( 30 ) NOT NULL,
 	PRIMARY KEY ( `PERSON_ID`,`USER_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`CREDITCARD_ADDRESS` (
 	`CREDIT_ID` BIGINT ( 30 ) NOT NULL, 
 	`ADDRESS_ID` BIGINT ( 30 ) NOT NULL,
 	PRIMARY KEY ( `CREDIT_ID`,`ADDRESS_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSON_CREDITCARD` (
 	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
 	`CREDITCARD_ID` BIGINT ( 30 ) NOT NULL,
 	PRIMARY KEY ( `PERSON_ID`,`CREDITCARD_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSON_EMAIL` (
 	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
 	`EMAIL_ID` BIGINT ( 30 ) NOT NULL,
 	PRIMARY KEY ( `PERSON_ID`, `EMAIL_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSON_PHONE` (
 	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
 	`PHONE_ID` BIGINT ( 30 ) NOT NULL,
 	PRIMARY KEY ( `PERSON_ID`, `PHONE_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  CREATE TABLE `BAZZAR`.`PERSON_REVIEW` (
  	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
  	`REVIEW_ID` BIGINT ( 30 ) NOT NULL,
  	PRIMARY KEY ( `PERSON_ID`, `REVIEW_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSON_QA` (
  	`PERSON_ID` BIGINT ( 30 ) NOT NULL, 
  	`QA_ID` BIGINT ( 30 ) NOT NULL,
  	PRIMARY KEY ( `PERSON_ID`, `QA_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 -- ----------------------------- Look Up Tables ------------------------------------
    CREATE TABLE `BAZZAR`.`SHOPPINGCART_STATUS_TYPE_LOOKUP` (
     	`CODE` VARCHAR ( 20 ) NOT NULL,
     	`VALUE` VARCHAR ( 50 ) NOT NULL,
    	PRIMARY KEY ( `CODE`),
    	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
   CREATE TABLE `BAZZAR`.`ORDER_STATUS_TYPE_LOOKUP` (
    	`CODE` VARCHAR ( 20 ) NOT NULL,
    	`VALUE` VARCHAR ( 50 ) NOT NULL,
   	PRIMARY KEY ( `CODE`),
   	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`CREDITCARD_TYPE_LOOKUP` (
  	`CODE` VARCHAR ( 20 ) NOT NULL,
  	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  CREATE TABLE `BAZZAR`.`ORDER_TYPE_LOOKUP` (
   	`CODE` VARCHAR ( 20 ) NOT NULL,
   	`VALUE` VARCHAR ( 50 ) NOT NULL,
  	PRIMARY KEY ( `CODE`),
  	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`MONTH_TYPE_LOOKUP` (
  	`CODE` VARCHAR ( 20 ) NOT NULL,
  	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`YEAR_TYPE_LOOKUP` (
  	`CODE` VARCHAR ( 20 ) NOT NULL,
  	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PERSONPREFIX_TYPE_LOOKUP` (
 	`CODE` VARCHAR ( 20 ) NOT NULL,
 	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`PHONE_TYPE_LOOKUP` (
 	`CODE` VARCHAR ( 20 ) NOT NULL,
 	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `BAZZAR`.`ADDRESS_TYPE_LOOKUP` (
 	`CODE` VARCHAR ( 20 ) NOT NULL,
 	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`EMAIL_TYPE_LOOKUP` (
 	`CODE` VARCHAR ( 20 ) NOT NULL,
 	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`CUSTOMER_TYPE_LOOKUP` (
 	`CODE` VARCHAR ( 20 ) NOT NULL,
 	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 CREATE TABLE `BAZZAR`.`NOTE_TYPE_LOOKUP` (
 	`CODE` VARCHAR ( 20 ) NOT NULL,
 	`VALUE` VARCHAR ( 50 ) NOT NULL,
 	PRIMARY KEY ( `CODE`),
 	INDEX ( `CODE` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;